global:
  environment: prod # Change to 'minikube' for local development

DB_USERNAME: "admin"
DB_PASSWORD: "password"

APP_DATABASE_NAME: "app_db"
APP_USERNAME: "app_user"
APP_PASSWORD: "app_password"

replicaCount: 2
image: mompansy/fyp-go-db-broker:latest
serviceAccount:
  create: true
  name: db-broker

resources:
  requests:
    memory: "256Mi"
  limits:
    memory: "512Mi"

keda:
  enabled: true
  pollingInterval: 15
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount: 10
  prometheus:
    serverAddress: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090
    query: sum(sandbox_databases_free)
    threshold: "3"

db-broker:
  app:
    name: db-broker
  service:
    name: db-broker
    port: 8080
  ingress:
    host: database-broker.com

web-app:
  app:
    name: web-app
    image: mompansy/fyp-node:latest
  service:
    name: web-app
    port: 3000
  ingress:
    host: queryproctor.com
    tlsSecret: web-app-tls

flask-app:
  app:
    name: flask-app
    image: mompansy/fyp-python:latest
  service:
    name: flask-app
    port: 5002

email: jaydenyeo.acs@gmail.com

certificate:
  commonName: queryproctor.com
  dnsNames:
    - queryproctor.com
    - www.queryproctor.com
  name: web-app-tls

cert-manager:
  name: lets-encrypt
  enabled: true # Set to false to disable cert-manager
