apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-init-scripts
  namespace: "{{ .Release.Namespace }}"
data:
  # This script runs during PostgreSQL initialization
  01-init-database.sql: |
    CREATE DATABASE app_db;
    CREATE USER app_user WITH PASSWORD 'app_password';
    GRANT CONNECT ON DATABASE app_db TO app_user;
    \c app_db;
    GRANT CREATE ON SCHEMA public TO app_user;
    GRANT USAGE ON SCHEMA public TO app_user;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO app_user;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO app_user;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO app_user;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO app_user;
