apiVersion: v1 
kind: Service
metadata:
  name: "{{ index .Values "flask-app" "service" "name" }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    app: "{{ index .Values "flask-app" "app" "name" }}"
  ports:
    - name: http
      port: 5000
      targetPort: {{ index .Values "flask-app" "service" "port" }}