apiVersion: v1
kind: Service
metadata:
  name: registry-server
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    app: registry-server
  ports:
    - name: http
      port: 80
      targetPort: 80
      # nodePort: 30080  # Optional: Uncomment to set a specific NodePort (30000-32767)
  type: NodePort
