apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ index .Values "db-broker" "app" "name" }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ index .Values "db-broker" "app" "name" }}"
  template:
    metadata:
      labels:
        app: "{{ index .Values "db-broker" "app" "name" }}"
    spec:
      serviceAccount: "{{ .Values.serviceAccount.name }}"
      containers:
        - name: db-broker
          image: "{{ .Values.image }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: NAMESPACE
              value: "{{ .Release.Namespace }}"
          resources: {{- toYaml .Values.resources | nindent 12 }}
