apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-server
  namespace: "{{ .Release.Namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-server
  template:
    metadata:
      labels:
        app: registry-server
    spec:
      containers:
        - name: registry-server
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: registry-config
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: registry-config
          configMap:
            name: registry
