[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.1",
    "frictionless>=5.18.1",
    "ruff>=0.12.2",
    "requests>=2.31.0",
    "flask-cors>=6.0.1",
    "gunicorn>=23.0.0",
]
