/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx';
import { Route as RegisterRouteImport } from './routes/register.tsx';
import { Route as LoginRouteImport } from './routes/login.tsx';
import { Route as StudentRouteImport } from './routes/_student.tsx';
import { Route as AdminRouteImport } from './routes/_admin.tsx';
import { Route as IndexRouteImport } from './routes/index.tsx';
import { Route as StudentStudentDashboardRouteImport } from './routes/_student.student.dashboard.tsx';
import { Route as AdminAdminProblemsRouteImport } from './routes/_admin.admin.problems.tsx';
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin.admin.dashboard.tsx';
import { Route as AdminAdminProblemIdRouteImport } from './routes/_admin.admin.problem.$id.tsx';

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const StudentStudentDashboardRoute = StudentStudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => StudentRoute,
} as any);
const AdminAdminProblemsRoute = AdminAdminProblemsRouteImport.update({
  id: '/admin/problems',
  path: '/admin/problems',
  getParentRoute: () => AdminRoute,
} as any);
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any);
const AdminAdminProblemIdRoute = AdminAdminProblemIdRouteImport.update({
  id: '/admin/problem/$id',
  path: '/admin/problem/$id',
  getParentRoute: () => AdminRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/admin/dashboard': typeof AdminAdminDashboardRoute;
  '/admin/problems': typeof AdminAdminProblemsRoute;
  '/student/dashboard': typeof StudentStudentDashboardRoute;
  '/admin/problem/$id': typeof AdminAdminProblemIdRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/admin/dashboard': typeof AdminAdminDashboardRoute;
  '/admin/problems': typeof AdminAdminProblemsRoute;
  '/student/dashboard': typeof StudentStudentDashboardRoute;
  '/admin/problem/$id': typeof AdminAdminProblemIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_admin': typeof AdminRouteWithChildren;
  '/_student': typeof StudentRouteWithChildren;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute;
  '/_admin/admin/problems': typeof AdminAdminProblemsRoute;
  '/_student/student/dashboard': typeof StudentStudentDashboardRoute;
  '/_admin/admin/problem/$id': typeof AdminAdminProblemIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/admin/problems'
    | '/student/dashboard'
    | '/admin/problem/$id';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/admin/problems'
    | '/student/dashboard'
    | '/admin/problem/$id';
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_student'
    | '/login'
    | '/register'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/problems'
    | '/_student/student/dashboard'
    | '/_admin/admin/problem/$id';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AdminRoute: typeof AdminRouteWithChildren;
  StudentRoute: typeof StudentRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  RegisterRoute: typeof RegisterRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_student': {
      id: '/_student';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof StudentRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_admin': {
      id: '/_admin';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_student/student/dashboard': {
      id: '/_student/student/dashboard';
      path: '/student/dashboard';
      fullPath: '/student/dashboard';
      preLoaderRoute: typeof StudentStudentDashboardRouteImport;
      parentRoute: typeof StudentRoute;
    };
    '/_admin/admin/problems': {
      id: '/_admin/admin/problems';
      path: '/admin/problems';
      fullPath: '/admin/problems';
      preLoaderRoute: typeof AdminAdminProblemsRouteImport;
      parentRoute: typeof AdminRoute;
    };
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard';
      path: '/admin/dashboard';
      fullPath: '/admin/dashboard';
      preLoaderRoute: typeof AdminAdminDashboardRouteImport;
      parentRoute: typeof AdminRoute;
    };
    '/_admin/admin/problem/$id': {
      id: '/_admin/admin/problem/$id';
      path: '/admin/problem/$id';
      fullPath: '/admin/problem/$id';
      preLoaderRoute: typeof AdminAdminProblemIdRouteImport;
      parentRoute: typeof AdminRoute;
    };
  }
}

interface AdminRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute;
  AdminAdminProblemsRoute: typeof AdminAdminProblemsRoute;
  AdminAdminProblemIdRoute: typeof AdminAdminProblemIdRoute;
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminProblemsRoute: AdminAdminProblemsRoute,
  AdminAdminProblemIdRoute: AdminAdminProblemIdRoute,
};

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);

interface StudentRouteChildren {
  StudentStudentDashboardRoute: typeof StudentStudentDashboardRoute;
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentStudentDashboardRoute: StudentStudentDashboardRoute,
};

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
