{{- if and (index .Values "cert-manager" "enabled" | default true) (ne .Values.global.environment "minikube") }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "{{ index .Values "cert-manager" "name"}}"
spec:
  acme:
    email: "{{ .Values.email }}"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: lets-encrypt-private-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - http01:
          ingress:
            ingressClassName: public
{{- end }}
